#!/bin/bash
PERSON1=$1
PERSON2=$2

echo "$PERSON1 :: hi how ru "
echo "${PERSON2} :: i am fine $PERSON1, how abt u "
echo "$PERSON1 :: what are u doing ${PERSON2} "
echo "$PERSON1 :: learning devops"
echo "${PERSON2} :: ok good , $PERSON1 "
