#!bin/bash

echo " all the values passd at run time are $@ "
echo "number of varbles passed $# "
echo " ur script anem $0 "
echo " current wrk dir $PWD "
echo " process id of the current script pid is : $$ "
sleep 100 &
echo " PID last run process is : $! "